"""Rust skeleton backend: SCA index → compilable crate of todo!() stubs.

- Ctx struct from ctx_schema (Option-wrapped fields, Default)
- one type alias per signature class
- CtxOp: the uniform normalized-context op type
- per item: skeleton fn + ctx wrapper (<name>_op) for module-level functions
- per group×signature class: a Vec<CtxOp> constructor (one element type per array)
- pipelines as ordered Vec<CtxOp>
"""

from __future__ import annotations

from findexer.generate.base import GeneratedFile, GeneratorBackend, GenOptions
from findexer.schema import Group, Item, ScaIndex

_RUST_KEYWORDS = {
    "as", "async", "await", "box", "break", "const", "continue", "crate", "dyn",
    "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let",
    "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "static",
    "struct", "super", "trait", "true", "type", "unsafe", "use", "where", "while",
}
_NO_RAW = {"self", "Self", "super", "crate"}


def _ident(name: str) -> str:
    out = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    if not out or out[0].isdigit():
        out = "_" + out
    if out in _NO_RAW:
        return out + "_"
    if out in _RUST_KEYWORDS:
        return "r#" + out
    return out


def _split_top(s: str) -> list[str]:
    parts, depth, cur = [], 0, ""
    for ch in s:
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur.strip())
    return parts


def rust_type(t: str) -> str:
    t = t.strip().lstrip("*")
    simple = {
        "str": "String", "bytes": "Vec<u8>", "bool": "bool", "i64": "i64",
        "f64": "f64", "unit": "()", "any": "serde_json::Value", "error": "String",
        # fn values can't cross the ctx boundary (no Default/Debug); carry as data
        "fn": "serde_json::Value",
    }
    if t in simple:
        return simple[t]
    if t.endswith(">") and "<" in t:
        base, args_s = t.split("<", 1)
        args = _split_top(args_s[:-1])
        base = base.strip()
        if base == "list" or base == "iter":
            return f"Vec<{rust_type(args[0])}>"
        if base == "map":
            return f"std::collections::HashMap<{rust_type(args[0])}, {rust_type(args[1]) if len(args) > 1 else 'serde_json::Value'}>"
        if base == "set":
            return f"std::collections::HashSet<{rust_type(args[0])}>"
        if base == "option":
            return f"Option<{rust_type(args[0])}>"
        if base == "result":
            err = rust_type(args[1]) if len(args) > 1 else "String"
            return f"Result<{rust_type(args[0])}, {err}>"
        if base == "tuple":
            if not args:
                return "()"
            return "(" + ", ".join(rust_type(a) for a in args) + ")"
    return "serde_json::Value"  # obj:<Name> and anything exotic


class RustBackend(GeneratorBackend):
    name = "rust"

    def generate(self, index: ScaIndex, options: GenOptions) -> list[GeneratedFile]:
        items = [
            i for i in index.items
            if options.group is None
            or i.group == options.group or i.group.startswith(options.group + ".")
        ]
        by_ordinal = {i.ordinal: i for i in items}
        aliases: dict[str, str] = {
            sig_id: f"Sig{n}" for n, sig_id in enumerate(sorted(index.signature_classes))
        }
        lines: list[str] = [
            "#![allow(dead_code, unused_variables, unused_mut, non_snake_case, unused_imports)]",
            f"//! Generated by findexer {index.findexer_version} from project "
            f"'{index.project_name}'. Bodies are todo!() stubs.",
            "",
            "#[derive(Debug)]",
            "pub enum OpError {",
            "    MissingCtxKey(&'static str),",
            "    Todo,",
            "}",
            "",
            "#[derive(Default, Debug)]",
            "pub struct Ctx {",
        ]
        for key in sorted(index.ctx_schema):
            lines.append(f"    pub {_ident(key)}: Option<{rust_type(index.ctx_schema[key])}>,")
        lines += [
            "}",
            "",
            "pub type CtxOp = Box<dyn FnMut(&mut Ctx) -> Result<(), OpError>>;",
            "",
            "// ---- signature classes (one element type per operation array) ----",
        ]
        for sig_id in sorted(index.signature_classes):
            sc = index.signature_classes[sig_id]
            params = ", ".join(rust_type(p) for p in sc["params"] if p)
            ret = sc["returns"]
            ret_s = "" if ret == "unit" else f" -> {rust_type(ret)}"
            lines.append(f"// {sig_id}")
            lines.append(f"pub type {aliases[sig_id]} = Box<dyn Fn({params}){ret_s}>;")
        lines.append("")

        generated_ops: list[tuple[str, str]] = []  # (fn path, ordinal ref) for arrays

        def emit_item(item: Item, indent: str, used: set[str]) -> list[str]:
            out: list[str] = []
            name = _ident(item.name)
            if name in used:
                name = f"{name}_o{item.ordinal}"
            used.add(name)
            doc = f" — {item.doc}" if item.doc else ""
            out.append(
                f"{indent}/// [{item.ordinal}] {item.address} "
                f"({item.file}:{item.span[0]}-{item.span[1]}, {item.language}, "
                f"{item.state_capture}→{item.rust_fn_trait}){doc}"
            )
            if item.kind in ("closure", "lambda"):
                out[-1] = out[-1].replace("///", "//")
                out.append(f"{indent}// internal item ({item.kind}) — not generated as a free fn")
                return out
            params = []
            if item.kind == "method":
                params.append("recv: &mut serde_json::Value")
            for p in item.signature.params:
                if p.kind in ("receiver", "kwvariadic"):
                    continue
                params.append(f"{_ident(p.name)}: {rust_type(p.norm_type)}")
            ret = item.signature.returns_norm
            ret_s = "" if ret == "unit" else f" -> {rust_type(ret)}"
            out.append(f"{indent}pub fn {name}({', '.join(params)}){ret_s} {{")
            out.append(f"{indent}    todo!()")
            out.append(f"{indent}}}")
            if item.kind == "function":
                out.append("")
                out.append(f"{indent}pub fn {name}_op() -> crate::CtxOp {{")
                out.append(f"{indent}    Box::new(move |ctx: &mut crate::Ctx| {{")
                call_args = []
                for p in item.signature.params:
                    if p.kind in ("receiver", "kwvariadic"):
                        continue
                    ctx_ref = item.ctx_adapter.param_map.get(p.name, f"ctx.{p.name}")
                    key = ctx_ref.removeprefix("ctx.")
                    field = _ident(key)
                    var = _ident(p.name)
                    if key in item.ctx_adapter.requires:
                        out.append(
                            f"{indent}        let {var} = ctx.{field}.clone()"
                            f".ok_or(crate::OpError::MissingCtxKey(\"{key}\"))?;"
                        )
                    else:
                        out.append(
                            f"{indent}        let {var} = ctx.{field}.clone().unwrap_or_default();"
                        )
                    call_args.append(var)
                out.append(f"{indent}        let result = {name}({', '.join(call_args)});")
                if item.ctx_adapter.return_key:
                    rk = _ident(item.ctx_adapter.return_key)
                    out.append(f"{indent}        ctx.{rk} = Some(result);")
                else:
                    out.append(f"{indent}        let _ = result;")
                out.append(f"{indent}        Ok(())")
                out.append(f"{indent}    }})")
                out.append(f"{indent}}}")
                mod_path = "::".join(_ident(p) for p in item.group.split("."))
                generated_ops.append((f"crate::{mod_path}::{name}_op()", item.address))
            return out

        op_arrays: list[str] = []

        def emit_group(group: Group, indent: str) -> list[str]:
            out: list[str] = []
            gname = _ident(group.name)
            out.append(f"{indent}pub mod {gname} {{")
            used: set[str] = set()
            member_items = [
                by_ordinal[o] for o in group.member_ordinals if o in by_ordinal
            ]
            for item in member_items:
                out.extend(emit_item(item, indent + "    ", used))
                out.append("")
            for child in group.children:
                out.extend(emit_group(child, indent + "    "))
            out.append(f"{indent}}}")
            # signature-homogeneous op arrays for this group
            fn_paths = {addr: path for path, addr in generated_ops}
            for n, sig_id in enumerate(sorted(group.op_arrays)):
                members = [
                    by_ordinal[o] for o in group.op_arrays[sig_id]
                    if o in by_ordinal and by_ordinal[o].kind == "function"
                ]
                refs = [fn_paths.get(m.address) for m in members]
                refs = [r for r in refs if r]
                if not refs:
                    continue
                arr_name = _ident(f"ops_{group.path.replace('.', '_')}_{n}")
                op_arrays.append(f"// {sig_id} — members: "
                                 + ", ".join(m.address for m in members))
                op_arrays.append(f"pub fn {arr_name}() -> Vec<crate::CtxOp> {{")
                op_arrays.append("    vec![" + ", ".join(refs) + "]")
                op_arrays.append("}")
            return out

        for root in index.groups:
            lines.extend(emit_group(root, ""))
            lines.append("")
        lines.append("// ---- operation groups (arrays partitioned by signature) ----")
        lines.extend(op_arrays)

        if index.pipelines:
            lines.append("")
            lines.append("// ---- ordered pipelines ----")
            fn_paths = {addr: path for path, addr in generated_ops}
            for pipe in index.pipelines:
                stages = [by_ordinal.get(o) for o in pipe.stages]
                refs = [fn_paths.get(s.address) for s in stages if s is not None]
                if not all(refs):
                    lines.append(f"// pipeline '{pipe.name}' skipped: stage(s) not generatable")
                    continue
                lines.append(f"pub fn pipeline_{_ident(pipe.name)}() -> Vec<crate::CtxOp> {{")
                lines.append("    vec![" + ", ".join(refs) + "]")
                lines.append("}")

        cargo = "\n".join([
            "[package]",
            f'name = "{_ident(index.project_name).strip("r#")}"',
            'version = "0.1.0"',
            'edition = "2021"',
            "",
            "[dependencies]",
            'serde_json = "1"',
            "",
        ])
        return [
            GeneratedFile("Cargo.toml", cargo),
            GeneratedFile("src/lib.rs", "\n".join(lines) + "\n"),
        ]
